### DISCUSSION TITLE
Can the data source be provisioned by version number?

### DISCUSSION THREAD

**Discussion by bunkiedc** [grafana/grafana-infinity-datasource#1074] [Q&A] [answered]
We use provisioning for our data sources, but I've notice that we get the latest one each time a new user gets added.  I would like to be able to stage first in dev before allowing it into production, but I don't see a way of including a version (like the graphiteVersion) in my provisioned yaml file.  Is there a way?

**Comment by yesoreyeram** [comment]
Can you explain more? What do you mean latest every time? How do you provision etc?

**Comment by bunkiedc** [comment]
I provision from a yaml file.  When a user is created, it deploys the grafana environment using the provisioned data source.  But it always picks the latest version available, instead of being able to have it in the provisioned yaml file.  I noticed that graphite has this capability e.g. graphiteVersion= "1.1".  I'd like to be able to do the same with infinity.  I now have new users using 2.11.4, and older ones using 2.11.3, so I'd like to be able to validate the updates before having the production environment use the latest.

**Reply by yesoreyeram** [reply]
In grafana cloud or on-pren deployment? Can you share the provisioning config? Provisioning is only for datasource not for plugin. So I suspect something wrong with your setup.

**Reply by yesoreyeram** [reply]
And datasources doesnt have version at all. Only plugins will have version

**Comment by bunkiedc** [comment]
I’m not at my computer at the moment, I can sent it tomorrow if it’s needed. What’s the 2.11.4 then?  The Manifest shows 2.11.3 on some of my deployments and some with 2.11.4.  This is the infinity plugin we’re talking about right?I’m deploying on-prem. Nothing is broken, it’s working fine. I just wanted to control what gets installed and when. David714-476-2692On Nov 28, 2024, at 14:02, Sriram ***@***.***> wrote:﻿
And datasources doesnt have version at all. Only plugins will have version

**Comment by bunkiedc** [comment]
### Here's the yaml I'm using.
```
apiVersion: 1
datasources:
  - id: 2
    name: "Infinity"
    type: "yesoreyeram-infinity-datasource"
    version: 1   
    orgId: 1
    uid: "myUIDxxxxxx"
    isDefault: "false"
    editable: "false"
    readOnly: "true"
    basicAuth: "false"
    basicAuthUser: ""
    jsonData:
      allowedHosts: 
       - "http://myHost:myPort"
      global_queries: []
      secureQueryName1: ""
    secureJsonData:
```
### What I've seen as far as graphite is concerned, is:
```
apiVersion: 1
datasources:
  - name: Graphite
    type: graphite
    access: proxy
    url: http://localhost:8080
    jsonData:
      graphiteVersion: '1.1'    <---- this is the version number to use
```
