### DISCUSSION TITLE
Data Source Plugin Not Working

### DISCUSSION THREAD

**Discussion by faisalwani01** [grafana/grafana-infinity-datasource#1247] [Q&A] [answered]
I am trying to use this plugin and provision it from source code
```
apiVersion: 1

datasources:
  - name: Infinity
    type: yesoreyeram-infinity-datasource
    access: proxy
    isDefault: false
    editable: true
    jsonData:
      config:
        allowed_hosts:
          - "abc.io"
          - "abc.com"
```

but when i deploy it to prod its giving me this error
<img width="1522" alt="inifinity" src="https://github.com/user-attachments/assets/771e7e02-e9ef-4eac-8075-f20a6173c3ae" />
