### DISCUSSION TITLE
Cannot Provision Alerts Using Infinity Plugin via YAML

### DISCUSSION THREAD

**Discussion by faisalwani01** [grafana/grafana-infinity-datasource#1250] [General]
Hi team,

I'm trying to provision an alert rule using the Grafana provisioning system (apiVersion: 1) with the Infinity plugin (yesoreyeram-infinity-datasource), but it doesn't seem to be working.

I'm following the same structure that works perfectly with my PostgreSQL alert provisioning, but for the Infinity plugin, no alert is created, and nothing appears in the "Alert Rules" UI after restarting Grafana.

Here’s an example of our working Postgres alert rule for context:
```
apiVersion: 1
groups:
  - orgId: 1
    name: ALERT_GROUP
    folder: some-folder
    interval: 60s
    rules:
      - uid: some-uid
        title: SOME_ALERT_TITLE
        condition: Some Query Ref
        data:
          - refId: Some Query Ref
            queryType: ''
            relativeTimeRange:
              from: 259200
              to: 0
            datasourceUid: postgres_datasource_uid
            model:
              format: table
              rawQuery: true
              rawSql: |
                SELECT count(*) FROM some_table WHERE conditions_here
              refId: Some Query Ref
          - refId: Expression Ref
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: "-100"
            model:
              conditions:
                - evaluator:
                    params: [0]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [Some Query Ref]
                  reducer:
                    type: last
                type: query
              datasource:
                type: __expr__
                uid: "-100"
              expression: A
              refId: Expression Ref
        dashboardUid: dashboard_uid
        panelId: 11
        noDataState: NoData
        execErrState: Alerting
        for: 5m
        annotations:
          description: Alert description here
          summary: Alert summary here
        labels:
          severity: critical

```

I’ve confirmed that:

1. The data source is reachable and returns the correct JSON
2. The dashboard and panel UIDs are correct
3. The same YAML works with Postgres as the data source

Questions:

1. Is YAML alert provisioning supported for the Infinity plugin?
2. Are there any limitations or additional config options required to enable alerting?
3. Should we be using the /api/v1/provisioning/alert-rules endpoint instead for plugin-based data sources?
4. Any clarification or guidance would be much appreciated.

Thanks!

**Comment by faisalwani01** [comment]
cc @yesoreyeram

**Reply by faisalwani01** [reply]
i have tried to create this for infinity plugin, but something seems off

```
apiVersion: 1
groups:
  - orgId: 1
    name: CustomAlerts
    folder: CustomFolder
    interval: 60s
    rules:
      - uid: sample-alert
        title: Sample Infinity Alert
        condition: InfinityCheck
        data:
          - refId: InfinityQuery
            datasourceUid: [redacted]
            queryType: ''
            relativeTimeRange:
              from: 3600
              to: 0
            model:
              type: json
              source: url
              method: GET
              url: https://example.com/api/metrics
              parser: json
              format: table
              refId: InfinityQuery
              fields:
                - name: count
                  selector: count
                  type: number

          - refId: InfinityCheck
            queryType: ''
            relativeTimeRange:
              from: 3600
              to: 0
            datasource:
              type: __expr__
              uid: "-100"
            model:
              expression: InfinityQuery
              type: classic_conditions
              conditions:
                - type: query
                  query:
                    params:
                      - InfinityQuery
                  reducer:
                    type: last
                  evaluator:
                    type: gt
                    params:
                      - 3
                  operator:
                    type: and

        noDataState: NoData
        for: 5m
        annotations:
          summary: Anomaly detected
        labels:
          severity: critical

```
