### DISCUSSION TITLE
Provisioning of datasource with custom HTTP headers

### DISCUSSION THREAD

**Discussion by mynameisted** [grafana/grafana-infinity-datasource#182] [Q&A]
-- UPDATE -- 
Resolved by looking into Grafana's custom HTTP headers, anyone looking for a similar answer may refer below:
```
    jsonData:
      httpHeaderName1: <<Header Key>>
    secureJsonData:
      httpHeaderValue1: <<Header Value>>
```
