### DISCUSSION TITLE
Json column selector with dot in key

### DISCUSSION THREAD

**Discussion by jeratora** [grafana/grafana-infinity-datasource#82] [Q&A] [answered]
Hello.

I'm trying to select a Json value whose key contains special characters such as `.` and `/`.
Eg: 
```yaml
    "items": [
        {
            "apiVersion": "v1",
            "kind": "Pod",
            "metadata": {
                "labels": {
                    "app": "notthisone",
                    "app.kubernetes.io/name": "thisone",
```

I'm a able to select `app` using `items` as root and `metadata.labels.app` as selector.
But I can't select `app.kubernetes.io/name`, using any kind of syntax. Using positional argument in labels is not an option as the order is not garanted.

Any help will be welcome.

Thanks in advance and have a nice day.
