### ISSUE TITLE
[BUG]  Auth not being used - invalid settings. configure allowed hosts in the authentication section

### ISSUE THREAD

**Issue by bunkiedc** [grafana/grafana-infinity-datasource#901]
## **Describe the Bug**

The plugin is provisioned to not use any auth, but when tested, it complains that the config is invalid, and to configure the "allowed hosts" in the authentication section.  When going to the Authentication section, it shows that no-auth is configured.

## **Steps to reproduce**
Set up a provisioned plug-in that doesn't use auth.

Provide steps to reproduce the issue.

**Note:** bugs will be fixed only if enough information provided to reproduce the issue!

## **Sample Data**
```
# config file version
apiVersion: 1
datasources:
  - id: 2
    uid: "redacted"
    orgId: 1
    name: "Infinity"
    type: "yesoreyeram-infinity-datasource"
    url: "http://redacted"
    basicAuth: false
    basicAuthUser: ""
    isDefault: false
    jsonData:
      httpHeaderName1: "redacted"
      global_queries: []
      secureQueryName1: ""
    readOnly: true
    secureJsonData:
      httpHeaderValue1: "redacted"

```
Provide a [link](https://gist.github.com) for sample data, or provide sample data bellow

## **Screenshots**
![Infinity_Invalid_hosts](https://github.com/grafana/grafana-infinity-datasource/assets/67663203/05fa5245-ac58-41ac-8bca-d128511d6b5c)

## **Version Details:**

- Grafana version : Grafana v9.5.15 (5f5a096c79a0200a4a2cddbb499c50095edc3401)

- Plugin version : 2.8.0 (keyId: 7e4d0c6a708866e7)

## **Additional context**

I've also noticed that there is an additional note that the url is deprecated, but I was not able to find any specific information
about that.

![Infinity_plugin_misc](https://github.com/grafana/grafana-infinity-datasource/assets/67663203/6a4ff1a9-e8f5-4fb4-99c8-4d652c64c1cd)
