### ISSUE TITLE
[Bug] Can't provision inifinity datasource

### ISSUE THREAD

**Issue by KevinDW-Fluxys** [grafana/grafana-infinity-datasource#945]
## **Describe the bug**

When trying to provision an infinity datasource through the grafana operator with a `GrafanaDatasource` CRD, I get a 400 error without further info. 
```
status:
  lastMessage: '[POST /datasources] addDataSource (status 400): {}'
```

## **Steps to reproduce**

Add a simple datasource through the grafana operator, for example: 
```
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: ds-test
  namespace: test
spec:
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: "yesoreyeram-infinity-datasource"
    type: "yesoreyeram-infinity-datasource"
    url: ""
    basicAuth: false
    basicAuthUser: ""
    jsonData:
      global_queries: []
```
## **Version Details:**

- Grafana version : v11.0.0
- Plugin version : 2.6.2

## **Additional context**
I have tried with multiple combinations of parameters, the example given above is the most simplistic (the one you get when clicking the `Provisioning Script` button on a new datasource.
